[[Task]]
uid = "01"
name = "input"
command = "/usr/bin/echo"
args = ["1"]
timeout = 3000
delay = 200
next = ["02"]
givestdout = true
readstdin = false

[[Task]]
uid = "02"
name = "increment by 1"
command = "/usr/bin/awk"
args = ["{ print $1 + 1 }"]
timeout = 3000
delay = 200
next = ["02.000", "02.100"]
givestdout = true
readstdin = true

[[Task]]
uid = "02.000"
name = "increment by 2"
command = "/usr/bin/awk"
args = ["{ print $1 + 2 }"]
timeout = 3000
delay = 200
next = ["02.001"]
givestdout = true
readstdin = true

[[Task]]
uid = "02.001"
name = "increment by 2"
command = "/usr/bin/awk"
args = ["{ print $1 + 2 }"]
timeout = 3000
delay = 200
next = ["03"]
givestdout = true
readstdin = true

[[Task]]
uid = "02.100"
name = "increment by 3"
command = "/usr/bin/awk"
args = ["{ print $1 + 3 }"]
timeout = 3000
delay = 200
next = ["02.101"]
givestdout = true
readstdin = true

[[Task]]
uid = "02.101"
name = "increment by 3"
command = "/usr/bin/awk"
args = ["{ print $1 + 3 }"]
timeout = 3000
delay = 200
next = ["03"]
givestdout = true
readstdin = true

[[Task]]
uid = "03"
name = "collate"
command = "/bin/bash"
args = ["-c", "arr=($(cat)); echo ${arr[@]}"]
timeout = 3000
delay = 200
next = ["04"]
givestdout = true
readstdin = true

[[Task]]
uid = "04"
name = "output"
command = "xargs"
args = ["notify-send"]
timeout = 3000
delay = 200
next = [""]
givestdout = false
readstdin = true
