[[Task]]
uid = "01"
name = "input"
command = "/usr/bin/python3"
args = ["-c", "print('aaaaaaaaaaaaaaaaaa')"]
timeout = 3000
delay = 200
next = ["02","03","04"]
givestdout = true
readstdin = false

[[Task]]
uid = "02"
name = "input"
command = "/usr/bin/python3"
args = ["-c", "import sys; data=sys.stdin.read(); print(f'Received: {data}');"]
timeout = 3000
delay = 200
next = []
givestdout = false
readstdin = true

[[Task]]
uid = "03"
name = "input"
command = "/usr/bin/xargs"
args = ["notify-send"]
timeout = 3000
delay = 200
next = []
givestdout = false
readstdin = true

[[Task]]
uid = "04"
name = "input"
command = "/usr/bin/tee"
args = ["/home/aos/temp/orchest-test-output.txt"]
timeout = 3000
delay = 200
next = []
givestdout = false
readstdin = true
