[[Task]]
uid = "m001"
name = "Map1"
file = "././TEMPLATE.orchest.task.toml"
timeout = 3000
delay = 200
next = ["m002"]
givestdout = true
readstdin = false

[[Task]]
uid = "m002"
name = "Map2"
file = "././TEMPLATE.orchest.task.toml"
timeout = 3000
delay = 200
next = [""]
givestdout = false
readstdin = true
